services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - "./jenkins_data/jenkins_home:/var/jenkins_home"
